name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
    
    - name: Install dependencies
      run: |
        uv pip install -e .[dev]
        uv pip install pyinstaller
    
    - name: Run tests
      run: |
        uv run pytest
    
    - name: Build binary
      run: |
        uv run pyinstaller --onefile --name autodoc autodoc/cli/main.py
        # On Windows, the binary will have .exe extension
        if [ "$RUNNER_OS" = "Windows" ]; then
          mv dist/autodoc.exe dist/autodoc-windows-x86_64.exe
        elif [ "$RUNNER_OS" = "macOS" ]; then
          mv dist/autodoc dist/autodoc-macos-x86_64
        else
          mv dist/autodoc dist/autodoc-linux-x86_64
        fi
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: autodoc-${{ runner.os }}-${{ matrix.python-version }}
        path: dist/autodoc*
        retention-days: 30
    
    - name: Create Release Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/autodoc*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
